#!/bin/sh

NAME="wmehanna/mongo-rs";

docker buildx build \
    --tag ${NAME}:latest \
    --tag ${NAME}:7.0.11 \
    --tag ${NAME}:7.0 \
    --tag ${NAME}:7 \
    --platform=linux/amd64,linux/arm64 \
    --builder multi \
    --push \
    .
